services:
  backend:
    build: ./backend
    container_name: 100hype-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - 100hype-net

  frontend:
    build: ./frontend
    container_name: 100hype-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - 100hype-net

networks:
  100hype-net:
    driver: bridge
