services:
  backend:
    build: ./backend
    container_name: invest-ai-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - invest-ai-net

  frontend:
    build: ./frontend
    container_name: invest-ai-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/api/v1
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - invest-ai-net

networks:
  invest-ai-net:
    driver: bridge